### ISSUE TITLE
<applet> makes IE11 prompt to install Java

### ISSUE THREAD

**Issue by falsefalse** [ljharb/html-element-map#3]
When `byConstructor` is called it triggers "Your Java needs update" in Internet Explorer 11 , because `getData` creates an `<applet>` element.

![lol java](https://user-images.githubusercontent.com/38544/55091350-41029f80-50e3-11e9-9620-86e464633a30.gif)

This is a problem because when this alert pops up it makes IE11 stop executing whatever it was executing, and this timeouts the test suite.

https://github.com/ljharb/html-element-map/blob/a9405d1254803a01a6bedf6cd9502653df9db8c9/getData.js#L24

**Comment by ljharb** [comment]
hmm, interesting. I'm not sure how to address that except perhaps explicitly rejecting `applet`, and failing to match it.

**Comment by falsefalse** [comment]
@ljharb this makes sense. I don't think anyone uses the lib to find the constructor for applet element, wdyt?

**Comment by ljharb** [comment]
I think it's probably best to just comment `applet` out, given the circumstances.
